server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miss-design/hello-project.git
          search-paths: config
          username: 2225453885@qq.com
          password: puxiong@1234
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/